# ブランチにプッシュされたときにこのワークフローが実行されます
name: AWS example workflow
on:
  push:
      branches:
      - main
env:
  BUCKET_NAME : "frontcdkstack-myfirstbucketb8884501-gqaa9naujpvi"
  AWS_REGION : "ap-northeast-1"
  # CloudFrontディストリビューションID
  CLOUDFRONT_DISTRIBUTION_ID: "E2S54XJYY13H00"  
# ジョブレベルまたはワークフローレベルで権限を追加できます
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    permissions:
      # JWTを要求するために必要です
      id-token: write   
      # actions/checkoutに必要です 
      contents: read    

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # Assume RoleのARN
          role-to-assume: ${{ secrets.AWS_IAM }}
          # セッション名
          role-session-name: samplerolesession
          # AWSリージョン
          aws-region: ${{ env.AWS_REGION }}
      - name: npm install
        # npm依存関係のインストール
        run: npm install
      
      - name: build
        # プロジェクトのビルド
        run: npm run build

      # ファイルをAWS S3にコピー
      - name:  Copy file to s3
        #ビルドされたファイルをS3にアップロード
        run: |
          aws s3 cp ./build s3://${{ env.BUCKET_NAME }}/ --recursive

      # CloudFrontキャッシュの無効化 
      - name: delete cash
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"